/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test05;

import java.io.FileInputStream;
import java.util.Properties;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import domain.Author;
import domain.Book;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        try {

            // Class.forName("com.mysql.cj.jdbc.Driver");

            // Connection con= DriverManager.getConnection( "jdbc:mysql://localhost:3306/Test01DB","root","dsystems01" );

            Properties properties = new Properties();

            try {
             
                System.out.println( "**** Reading... ****" );
                properties.load( new FileInputStream("/home/dsystems01/Desktop/Java/hibernate.cfg.properties") );

            }
            catch ( Exception e ) {
                
                e.printStackTrace();

            }

            System.out.println( "**** Configuration ****" );
            Configuration configuration = new Configuration().addProperties( properties );

            System.out.println( "**** Configuration Read ****" );


            //**** Begin the next code braak the native run of this app ****
            configuration.addAnnotatedClass( Author.class );
            configuration.addAnnotatedClass( Book.class );
            //**** End the next code braak the native run of this app ****
            
            // //configuration.configure( new File( "/home/dsystems01/Desktop/Java/hibernate.cfg.properties" ) );
            // //configuration.addAnnotatedClass( Author.class );
            // //configuration.addAnnotatedClass( Book.class );

            // // Create Session Factory
            System.out.println( "**** SessionFactory ****" );
            SessionFactory sessionFactory = configuration.buildSessionFactory();

            // // Initialize Session Object

            System.out.println( "**** Open session ****" );
            Session session = sessionFactory.openSession();

            System.out.println( "**** Begin transaction ****" );
            var transaction = session.beginTransaction();
            
            // //

            System.out.println( "**** Commit ****" );
            transaction.commit();

            System.out.println( "**** Close ****" );
            sessionFactory.close();

        }
        catch ( Exception exception ) {

            System.out.println( "**** Error ****" );
            exception.printStackTrace();

        }


        System.out.println(new App().getGreeting());
        try {
           System.in.read();
        }
        catch ( Exception ex ) {

        }
    }
}
